name: Daily Tasks

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # City discovery shouldn't take long
    environment: prod
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run daily tasks
        run: npm run schedule:daily
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/sources/*/data/
          git diff --staged --quiet || git commit -m "Update city data [skip ci]"
          git push

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: daily-logs
          path: |
            *.log
          retention-days: 7
