name: Sync Events

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Sync events
        run: npm run sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Upload results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: sync-errors
          path: |
            *.log
            results/*.json
          retention-days: 7
